name: Build and Push Docker Image with OCI Labels and Attestation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: manoj_snyk
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Build and push Docker Image 1 (with OCI Label)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: .github/workflows/Dockerfile
        push: true
        tags: quay.io/manoj_snyk/test-repo-2/image1:latest
        labels: org.opencontainers.image.source=https://bitbucket.org/nikhilmane_crest/new_project/src/master/
    - name: Build and push Docker Image 2 (with Attestation)
      run: |
        docker buildx build --provenance=true --tag quay.io/manoj_snyk/test-repo-2/image2:latest --push -f .github/workflows/Dockerfile .
