name: Build and Push Docker Image to Nexus via Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Nexus Container Registry
      uses: docker/login-action@v2
      with:
        registry: https://4704-122-169-42-28.ngrok-free.app/repository/my-docker-repo/v2/
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Build and push Docker Image 1 (with OCI Label)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: .github/workflows/Dockerfile
        push: true
        tags: https://4704-122-169-42-28.ngrok-free.app/repository/my-docker-repo/v2/image1:latest
        labels: org.opencontainers.image.source=https://bitbucket.org/your_project/source

    - name: Build and push Docker Image 2 (with Attestation)
      run: |
        docker buildx build --provenance=true --tag https://4704-122-169-42-28.ngrok-free.app/repository/my-docker-repo/v2/image2:latest --push -f .github/workflows/Dockerfile .
